# Generated by Django 4.1.7 on 2023-04-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muster', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/meeps/'),
        ),
    ]
